### ISSUE TITLE
Channel: Rollover videos

### ISSUE THREAD

**Issue by jasonwiener** [37teams/vidycast-public#1]
When you roll over videos there's a broken image
![Screen Shot 2020-05-15 at 11 23 45 AM](https://user-images.githubusercontent.com/204083/82083739-108f1380-969f-11ea-84cb-3e0f84eadf19.png)
![Screen Shot 2020-05-15 at 11 24 08 AM](https://user-images.githubusercontent.com/204083/82083747-138a0400-969f-11ea-89de-290a1b89d4bb.png)
![Screen Shot 2020-05-15 at 11 01 52 AM](https://user-images.githubusercontent.com/204083/82083764-1ab11200-969f-11ea-8c1c-83f0222f4c6c.png)

**Comment by MikeLindenau** [comment]
Thanks for the tip on max width. Pushing fix now.

**Comment by MikeLindenau** [comment]
This should be fixed. If your still having issues we can reopen.
